Core/urls.py
 
from django.urls import path
 
from .views import *
 
app_name = "Core"
urlpatterns = [
    path('',index,name="home"),
    path('login/',login,name="login"),
    path('signup/',signup,name="signup"),
    path("forgotPassword/",forgotPassword,name="forgotPassword"),
    path("UserProfile",edit_user,name="edit_user"),
    path("ChangePassword",change_password,name="change_password"),
    path("logout",logout,name="logout"),
]

LinkFree/urls.py
 
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('',include("Core.urls")),
    path('',include("LinkPage.urls")),
    path('admin/', admin.site.urls),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

LinkPage/urls.py
 
from django.urls import path
 
from .views import *
 
app_name = "LinkPage"
handler404 = 'LinkPage.views.handler404'
urlpatterns = [
    path("Browse",browse,name="browse"),
    path("createPage",createPage,name="createPage"),
    path("updatePage",updatePage,name="updatePage"),
    path("DeletePage",DeletePage,name="DeletePage"),
    path("page/<uuid:uuid>/",linkpage_details,name="linkpage_details")
     
]

templates/pages/browse.html
{% extends 'base.html' %}

{% block title %}Browse Other Page {% endblock title %}
{% block content %}
    <h1 class="font-mono text-2xl text-center...">To Be Implemented</h1>
{% endblock %}

templates/pages/create.html
{% extends 'base.html' %}

{% block title %}Creafte A Page {% endblock title %}
{% block content %}

    <h1 class="font-semibold font-mono text-2xl text-center">Create Your First LinkTree Page</h1>
    {% if  mode == 1%}
        <script>
            toastr.success("The Page Has Been Created ")
        </script>
    {% endif %}
    <form method="POST" action="">
        {% csrf_token %}
        <div class="mt-4 flex justify-center ">
            
            <div  id="list_links" class="w-[28em]">
    
                <input  name="title" type="text" class="w-full  border border-slate-200 rounded-lg px-5 py-1 focus:outline-none focus:border-slate-500 hover:shadow" placeholder="Page Title Here  " required> 
                <br>
                <br>

                <div class="flex justify-between">
                    <select name="links[0][type]" class="py-2 px-3 cursor-pointer text-center text-white bg-blue-500 rounded-md">
                        <option value="Facebook">Facebook</option>
                        <option value="Instagram">Instagram</option>
                        <option value="Whatsapp">Whatsapp</option>
                        <option value="Youtube">Youtube</option>
                        <option value="Linkedin">Linkedin</option>
                        <option value="Github">Github</option>
                        <option value="Gmail">Gmail</option>
                        <option value="Others">Others</option>
                    </select>
                    <input  name="links[0][url]" type="text" class="w-full  border border-slate-200 rounded-lg px-5 py-1 focus:outline-none focus:border-slate-500 hover:shadow" placeholder="The Url" required> 
                    <button class="text-center   py-2 px-6 bg-red-600 hover:bg-red-700 text-sm text-white  rounded-md transition duration-200" >X</button>

                </div>
            
                <!--We Are adding here-->

            </div>
            
        </div>
        <br>
        <div class="flex justify-center">

            <button id="add_link" class="hidden lg:inline-block py-2 px-6 bg-green-600 hover:bg-green-700 text-sm text-white  rounded-md transition duration-200">Add Another Link</button>
        </div>
        <br>
        <div class="flex justify-center">
            <button class="text-center   py-2 px-6 bg-red-600 hover:bg-red-700 text-sm text-white  rounded-md transition duration-200" >Finsish</button>
        </div>

    </form>
 
    
    <script>
        var add_link = document.getElementById("add_link")
        var list_links = document.getElementById("list_links")
        var link_list_counter= 0
        add_link.addEventListener("click",(e)=>{
            e.preventDefault()
       
            var newRow = document.createElement("div")
            link_list_counter++;
            newRow.className = "py-1 flex justify-between"
            newRow.innerHTML = '<select name="'+`links[${link_list_counter}][type]`+'" class="py-2 px-3 cursor-pointer text-center text-white bg-blue-500 rounded-md">\
                            <option value="Facebook">Facebook</option>\
                            <option value="Instagram">Instagram</option>\
                            <option value="Whatsapp">Whatsapp</option>\
                            <option value="Youtube">Youtube</option>\
                            <option value="Linkedin">Linkedin</option>\
                            <option value="Github">Github</option>\
                            <option value="Gmail">Gmail</option>\
                            <option value="Others">Others</option>\
                        </select>\
                        <input name="'+`links[${link_list_counter}][url]`+'" type="text" class="w-full  border border-slate-200 rounded-lg px-5 py-1 focus:outline-none focus:border-slate-500 hover:shadow" placeholder="The Url" required> \
                        <button class="remove-button text-center py-2 px-6 bg-red-600 hover:bg-red-700 text-sm text-white rounded-md transition duration-200">X</button>';
                
            list_links.appendChild(newRow)
            
            list_links.addEventListener("click",(e)=>{
                if(e.target && e.target.classList.contains("remove-button")){
                    e.target.parentNode.remove()
                }
            })
        })
         
    </script>
{% endblock %}
 

templates/pages/delete.html
{% extends 'base.html' %}

{% block title %}Delete Your Pages {% endblock title %}
{% block content %}

    <h1 class="font-semibold font-mono text-2xl text-center">Delete Your LinkTree Pages</h1>
 
        
<form method="POST" action="">
    {% csrf_token %}
    <h1 class="font-light font-mono text-xl text-center">You Have About {{ Pageslength }} LinkTree Pages</h1>
    <div class="mt-4 flex justify-center">
        <div id="list_links" class="w-[28em]">
            <div class="relative overflow-x-auto">
                <table class="font-mono text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-5 py-2">
                                Page Id
                            </th>
                            <th scope="col" class="px-5 py-2">
                                Page Name
                            </th>
                            <th scope="col" class="px-5 py-2">
                                Created At
                            </th>
                            <th scope="col" class="px-5 py-2">
                            </th><th scope="col" class="px-5 py-2">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for linkpage in linkPages %}
          
                            <tr id="LinkPage{{ linkpage.id }}" class="bg-white border-b">
                                <td class="px-6 py-4">
                                    {{ linkpage.id }}
                                </td>
                                <th scope="row" class="px-6 py-4 font-medium  whitespace-nowrap text-[#282c34]">
                                    {{ linkpage.title }}
                                </th>
                                <td class="px-6 py-4">
                                    {{ linkpage.created_at }}
                                </td>
                                <td>
                                    <button data-page-id="{{ linkpage.id }}"
                                        class="remove-button text-center py-1 px-3 bg-red-600 hover:bg-red-700 text-sm text-white rounded-md transition duration-200">X</button>
                                    <!-- Add a hidden input field for each row -->
                                    <input type="hidden" name="selectedPageId" id="selectedPageId{{ linkpage.id }}">
                                </td>
                                <td>
                                    <a href="{% url 'LinkPage:linkpage_details' uuid=linkpage.uuid %}"
                                        class="text-center py-1 px-3 bg-green-600 hover:bg-hreen-700 text-sm text-white rounded-md transition duration-200">>></a>
                                    <!-- Add a hidden input field for each row -->
                                </td>
                            </tr>
 
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</form>
    <script>
     document.querySelectorAll(".remove-button").forEach(function(button) {
            button.addEventListener("click", function(e) {

                e.preventDefault()
                var pageId = this.getAttribute("data-page-id");
                alert()
                if (confirm("Are you sure you want to delete this page?")) {
                    
                    document.querySelector("#selectedPageId" + pageId).value = pageId;
                    // If user confirms, submit the form
                    document.querySelector("form").submit();
                     
                }
                else{
                    e.preventDefault()
                }
                
            });
        });
       
    </script>
{% endblock %}
 

templates/pages/linkpage_details.html
{% extends 'base.html' %}

{% block title %}Delete Your Pages {% endblock title %}
{% block content %}
<div class="flex flex-col items-center">
    <h1 class="font-mono text-2xl text-center">Page Title: <span class="font-semibold">{{linkpage.title}}</span></h1>
    <br>|
    <h1 class="font-mono text-2xl text-center">Create At :<span class="font-semibold">{{linkpage.created_at}}</span></h1>
</div>
    <div class="mt-4 flex justify-center">
        <table>
            <thead class="text-sm text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-5 py-2">
                        Link Type
                    </th>
                    <th scope="col" class="px-5 py-2">
                        Link 
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for link in links %}
                <tr>
                    
                    <td scope="col" class="px-5 py-2">
                        {{link.type}}
                    </td>
                    <td scope="col" class="px-5 py-2">
                        <a  class="text-violet-400"href="{{link.url}}" target="_blank">{{link.url}}</a>
        
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
                
        </div>
    </div>
 
    <script>
     
    </script>
{% endblock %}
 

templates/pages/update.html
{% extends 'base.html' %}

{% block title %}Modify Your Page {% endblock title %}
{% block content %}

    <h1 class="font-semibold font-mono text-2xl text-center">Modify Your LinkTree Page</h1>
 
        <form method="POST" action="">
            {% csrf_token %}
            <div class="mt-4 flex justify-center ">
                
                <div  id="list_links" class="w-[28em]">
        
                    <input  value="{{title}}" name="title" type="text" class="w-full  border border-slate-200 rounded-lg px-5 py-1 focus:outline-none focus:border-slate-500 hover:shadow" placeholder="Page Title Here  " required> 
                    <br>
                    <br>
                    {% for link in links %}
                      
                        <div class="flex justify-between mt-3">
                            <select id="type" name="links[0][type]" class="py-2 px-3 cursor-pointer text-center text-white bg-blue-500 rounded-md">
                                <option value="Facebook">Facebook</option>
                                <option value="Instagram">Instagram</option>
                                <option value="Whatsapp">Whatsapp</option>
                                <option value="Youtube">Youtube</option>
                                <option value="Linkedin">Linkedin</option>
                                <option value="Github">Github</option>
                                <option value="Gmail">Gmail</option>
                                <option value="Others">Others</option>
                            </select>
                            <input  name="links[0][url]" type="text" class="w-full  border border-slate-200 rounded-lg px-5 py-1 focus:outline-none focus:border-slate-500 hover:shadow" value="{{link.url}}" placeholder="The Url" required> 
                            <button class="text-center   py-2 px-6 bg-red-600 hover:bg-red-700 text-sm text-white  rounded-md transition duration-200" >X</button>
                        </div>
                        
                    {% endfor %}
                   
                
                    <!--We Are adding here-->

                </div>
                
            </div>
             <br>
            <div class="flex justify-center">

                <button id="add_link" class="hidden lg:inline-block py-2 px-6 bg-green-600 hover:bg-green-700 text-sm text-white  rounded-md transition duration-200">Add Another Link</button>
            </div>
            <br>
            <div class="flex justify-center">
                <button class="text-center   py-2 px-6 bg-red-600 hover:bg-red-700 text-sm text-white  rounded-md transition duration-200" >Finsish</button>
            </div>

        </form>
 
 
    <script>
        window.addEventListener("load",()=>{
            selects = document.querySelectorAll("#type")
          
           {% for  link in links %}
                selects[{{ forloop.counter0 }}].value = "{{link.type}}"
           
           {% endfor %}
             
    
            var add_link = document.getElementById("add_link")
            var list_links = document.getElementById("list_links")
            var link_list_counter= 0
            add_link.addEventListener("click",(e)=>{
                e.preventDefault()

                var newRow = document.createElement("div")
                link_list_counter++;
                newRow.className = "py-1 flex justify-between"
                newRow.innerHTML = '<select name="'+`links[${link_list_counter}][type]`+'" class="py-2 px-3 cursor-pointer text-center text-white bg-blue-500 rounded-md">\
                                <option value="Facebook">Facebook</option>\
                                <option value="Instagram">Instagram</option>\
                                <option value="Whatsapp">Whatsapp</option>\
                                <option value="Youtube">Youtube</option>\
                                <option value="Linkedin">Linkedin</option>\
                                <option value="Github">Github</option>\
                                <option value="Gmail">Gmail</option>\
                                <option value="Others">Others</option>\
                            </select>\
                            <input name="'+`links[${link_list_counter}][url]`+'" type="text" class="w-full  border border-slate-200 rounded-lg px-5 py-1 focus:outline-none focus:border-slate-500 hover:shadow" placeholder="The Url" required> \
                            <button class="remove-button text-center py-2 px-6 bg-red-600 hover:bg-red-700 text-sm text-white rounded-md transition duration-200">X</button>';
                    
                list_links.appendChild(newRow)

                list_links.addEventListener("click",(e)=>{
                    if(e.target && e.target.classList.contains("remove-button")){
                        e.target.parentNode.remove()
                    }
                })
            })
        })
        
         
    </script>
{% endblock %}
 