Core/urls.py
 
from django.urls import path
 
from .views import *
 
app_name = "Core"
urlpatterns = [
    path('',index,name="home"),
    path('login/',login,name="login"),
    path('signup/',signup,name="signup"),
    path("forgotPassword/",forgotPassword,name="forgotPassword"),
    path("UserProfile",edit_user,name="edit_user"),
    path("ChangePassword",change_password,name="change_password"),
    path("logout",logout,name="logout"),
]

LinkFree/urls.py
 
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('',include("Core.urls")),
    path('',include("LinkPage.urls")),
    path('admin/', admin.site.urls),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class NewUserInfo(models.Model):
    userId = models.OneToOneField(User,on_delete=models.CASCADE)
    userBio = models.TextField(blank=True)

Core/views.py
from django.shortcuts import render,redirect
from django.core.mail import EmailMessage
from django.contrib.auth.models import User
from django.contrib.auth import login as auth_login,logout as auth_logout
from django.contrib.auth.decorators import login_required
from .models import NewUserInfo
# Create your views here.
def index(request):
    return render(request,"core/index.html",{})

def login(request):
    if request.method == "POST":
            
        email = request.POST.get("email")
        password  = request.POST.get("password")
        try:
            user = User.objects.get(email=email,password=password)
            
            if user.is_active:
                auth_login(request,user)
                return render(request,"core/index.html",{})
        except Exception as error: 
            mode = 1
            print("exception is fucked right in the ass",error)
            return render(request,"core/login.html",{"mode":mode})
    else:
        return render(request,"core/login.html",{})
def signup(request):
    if request.method == "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password")
        password1 = request.POST.get("password1")
        
        res = {}
        if User.objects.filter(email=email):
            print("Email Already Exists FGT")
            res["mode"] = 3
        elif password != password1:
            print("password arenot the same")
            res["mode"] = 1
        else:
            user = User.objects.create_user(username,email)
            user.password = password
         
            user_bio = NewUserInfo(userId=user)
            print(f"user created with id {user.pk}:{user.id}")
            print(f"UserInfo Created With Id {user_bio.id}")

            res["mode"] = 2
            user.save()
            user_bio.save()
        return render(request,"core/signup.html",{"res":res})
    else:
       
        return render(request,"core/signup.html",{})

def forgotPassword(request):
    if request.method == "POST":
        email = request.POST.get("email")
        if User.objects.filter(email=email):
            user = User.objects.get(email=email)
    
            EmailMessage(
                subject="Password Reset",
                body="<b>The Password For your Account Is "+user.password,
                from_email="carti.youness65@gmail.com",
                to=[email]
            ).send()
        else:
            print(email)
            print(User.objects.all().values())
    return render(request,'core/forgot_pass.html',{})

def change_password(request):
    mode = None # 1 password changed #2 password is wrong #3 password aren't the same
    if request.method == "POST":
        oldpassword = request.POST.get("oldpassword")
        newpassword = request.POST.get("newpassword")
        confpassword = request.POST.get("confpassword")
        try:
           
            user = User.objects.get(id=request.user.id,password=oldpassword)
            if newpassword == confpassword:
                user.password = newpassword
                user.save()
                mode = 1
            else:
                print(f"{newpassword}=={confpassword}")
                mode = 3
        except Exception as error:
            mode = 2
            print(f"The error is [{error}]")
    return render(request,"core/change_password.html",{"mode":mode})

def edit_user(request):
    if request.method == "POST":
        first_name = request.POST.get("fname")
        last_name = request.POST.get("lname")
        username = request.POST.get("username")
        bioText = request.POST.get("bio")
        #
        user = User.objects.get(id=request.user.id)
        userInfo = NewUserInfo.objects.get(userId=request.user.id)

        user.first_name = first_name
        user.last_name = last_name
        user.username = username
        userInfo.userBio = bioText

        user.save()
        userInfo.save()

        print(user)

    bio = NewUserInfo.objects.get(userId=request.user.id)
    return render(request,"core/edit_user.html",{"bio":bio.userBio})
        

@login_required()
def logout(request):
    auth_logout(request) 
    return render(request,"core/index.html",{})
 

templates/core/change_password.html
{% extends 'base.html' %}

{% block title %}Create A Page {% endblock title %}
{% block content %}
     {% if mode == 1 %}
    <script>
        toastr.success('Your Password Has Been Changed')
    </script>
    {% elif mode == 2 %}
    <script>
        toastr.error('Your Old Password Is Wrong')
    </script>
    {% elif mode == 3 %}
    <script>
        toastr.error('The New and Cofirm New fields aren\'t the same')
    </script>
    {% endif %}
 
    <h1 class="font-semibold font-mono text-2xl text-center">Change Your Password Now</h1>
    <!-- component -->
 <div class="max-w-lg mx-auto my-10 bg-white p-8 rounded-xl shadow shadow-slate-300">
 
        <form method="POST" action="" class="my-10">
            {% csrf_token %}
            
            <div class="flex flex-col space-y-5">
                <label for="oldpassword">
                    <p class="font-medium text-slate-700 pb-2">Old Password</p>
                    <input  name="oldpassword" type="password" class="w-full py-3 border border-slate-200 rounded-lg px-3 focus:outline-none focus:border-slate-500 hover:shadow" placeholder="Old Password" required>
                </label>
                <label for="newpassword">
                    <p class="font-medium text-slate-700 pb-2">New Password</p>
                    <input  name="newpassword" type="password" class="w-full py-3 border border-slate-200 rounded-lg px-3 focus:outline-none focus:border-slate-500 hover:shadow" placeholder="New Password" required>
                </label><label for="confirmnewpassword">
                    <p class="font-medium text-slate-700 pb-2">Confirm New Password</p>
                    <input  name="confpassword" type="password" class="w-full py-3 border border-slate-200 rounded-lg px-3 focus:outline-none focus:border-slate-500 hover:shadow" placeholder="Confirm New Password" required>
                </label>
                <button class="w-full py-3 font-medium text-white bg-yellow-500 hover:bg-yellow-700 rounded-lg border-indigo-500 hover:shadow inline-flex space-x-2 items-center justify-center">
                     
                      
                      <span>Reset password</span>
                </button>
         
            </div>
        </form>
    </div> 
{% endblock %}

templates/core/edit_user.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Edit Your Profile  {% endblock title %}
{% block content %}
 <!-- component -->
<!-- component -->
<div class="  min-h-screen pt-2 font ">
    <div class="container mx-auto">
        <div class="inputs w-full max-w-2xl p-6 mx-auto">
            <a href="{% url 'Core:edit_user' %}" class="flex justify-center">
                <div class="relative w-14 h-14 overflow-hidden   bg-[#282c34] rounded-full ">
                    <svg class="absolute w-15 h-15 text-white  " fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
                </div>
            </a>
            <h2 class="text-2xl text-gray-900">Account Setting</h2>
            <form method="POST" action="" class="mt-6 border-t border-gray-400 pt-4">
                {% csrf_token %}
                <div class='flex flex-wrap -mx-3 mb-6'>
                    <div class='w-full md:w-full px-3 mb-6'>
                        <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2' for='grid-text-1'>email address</label>
                        <input class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='text' placeholder='Enter email' value="{{user.email}}" name="email"  disabled>
                    </div>

                    <div class='w-full md:w-full px-3 mb-6 '>
                        <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>password</label>
                        <a href="{% url 'Core:change_password' %}" class="appearance-none bg-yellow-500 text-white px-3 py-2 shadow-sm border border-gray-400 rounded-md">Change your Password</a>
                    </div>
                      
                    <div class="personal w-full border-t border-gray-400 pt-4">
                        <h2 class="text-2xl text-gray-900">Personal info:</h2>
                        <div class="flex items-center justify-between mt-4">
                            <div class='w-full md:w-1/2 px-3 mb-6'>
                                <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2' >first name</label>
                                <input class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='text' value="{{user.first_name}}" name="fname">
                            </div>
                            <div class='w-full md:w-1/2 px-3 mb-6'>
                                <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2' >last name</label>
                                <input class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='text' value="{{user.last_name}}" name="lname"   required>
                            </div>
                        </div>
                        <div class='w-full md:w-full px-3 mb-6'>
                            <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>user name</label>
                            <input class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='text'  value="{{user.username}}" name="username"  required>
                        </div>
                        <div class='w-full md:w-full px-3 mb-6'>
                            <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2' >Bio</label>
                            <textarea class='bg-gray-100 rounded-md border leading-normal resize-none w-full h-20 py-2 px-3 shadow-inner  border-gray-400 font-medium placeholder-gray-700 focus:outline-none focus:bg-white' name="bio"  required>{{bio}}</textarea>
                        </div>
                        <div class="flex justify-end">
                            <button class="block px-3 py-2 mb-2 leading-loose text-xs text-center text-white font-bold bg-green-600 hover:bg-green-700  rounded-md" href="{% url 'Core:edit_user' %}">Save Changes</button>
    
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/core/forgot_pass.html
{% extends 'base.html' %}

{% block title %}For Password  {% endblock title %}
{% block content %}
<div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="py-3 text-3xl text-center">Forgot Password</h1>
    <div class="flex justify-center">
        <form method="POST" action="" class="py-3">
            {% csrf_token %}
            <table class="mb-9">
                <tr class="mb-9">
                    <td><label class="inline-block mb-2">Email :&nbsp;&nbsp;&nbsp;</label></td>
                    <td class="w-[20rem]">
                        <input type="text" name="email" class="w-full py-2 px-6 rounded-xl border-2">
                    </td>
                </tr>
 
            </table>
            <p class="text-xs text-center"><b>Note :</b>That If the Account doesn't exist you have 10 seconds to <br>get the fuck out from here <p>
                <br>
            <div class="flex justify-center">
                <button class="py-2 px-4  bg-green-500 hover:bg-green-700 rounded-xl  text-white">Send Password</button>
            </div>
        </form>
    </div>
     
</div>
{% endblock %}

templates/core/index.html
 
{% extends "base.html" %}

{% block title %} Home {% endblock title %}
{% load static %}
{% block content %}
    <section class=" bg-gradient-to-r from-green-500 to-green-600 ">
        <br>
        <br>
        <br>
        <br>
        <div class="flex justify-center items-center text-center w-[100%] h-[10rem]  bg-gradient-to-r   ">
            
            <p class="text-white text-3xl font-metro-bold drop-shadow-4xl">Welcome To The LinkFee app that allows users to create personalized <br>profile pages featuring links to their social media profiles, websites, and<br> online content. .<br>  </p>
            
        </div>
        <div class="flex justify-center">
            <a href="{% url 'Core:signup' %}" class="py-3 px-6  bg-white hover:bg-gray-200 rounded-md  text-green-500 text-2xl">Start Now</a>

        </div>
        <br>
        <br>
        <br>
        <br>
    </section>
 
{% endblock   %}  

templates/core/login.html
{% extends 'base.html' %}

{% block title %}Login {% endblock title %}
{% block content %}
    <div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-md">
        {% if mode == 1%}
            <script>
                toastr.error('The Email Or the Password Is Incorrect You Guess ')
            </script>
        {% endif %}
        <h1 class="py-3 text-3xl text-center">Login</h1>
        <div class="flex justify-center">
            <form method="POST" action="" class="py-3">
                {% csrf_token %}
                {% if forms.error %}
                <ul class="text-center bg-red-500 text-white py-3 px-4 rounded-lg">
                    {{form.errors}}
                </ul>
                {% endif %}
                <table class="mb-9">
                    <tr class="mb-9">
                        <td><label class="inline-block mb-2">email :&nbsp;&nbsp;&nbsp;</label></td>
                        <td class="w-[20rem]">
                            <input type="email" name="email" class="w-full py-2 px-6 rounded-md border-2" required>
                        </td> 
                    </tr>
 
                    <tr class="mb-9">
                        <td><label class="inline-block mb-2">Password :&nbsp;&nbsp;&nbsp;</label></td>
                        <td class="w-[20rem]">
                            <input type="password" name="password" class="w-full py-2 px-6 rounded-md border-2" required>
                        </td>
                    </tr>
                    
                </table>
                <div class="flex justify-center">
                    <button class="py-2 px-4 text-lg bg-green-500 hover:bg-red-700 rounded-md  text-white">Log  In</button>
                </div>
            </form>
        </div>
        <div class="flex justify-center">
            <a href="{% url 'Core:forgotPassword' %}" class="text-center">Forgot Password ? </a>
        </div>
    </div>
{% endblock content %}

templates/core/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock title %}
{% block content %}
    <div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-md">
        {% if res %}
            {% if  res.mode == 2 %}
                {% comment %} <p class="py-2 px-4 text-center rounded-lg bg-green-500 text-white">Your account has been created successfully</p> {% endcomment %}
                <script>
                    
                    toastr.success('Your account has been created successfully ')
                </script>
                {% else %}
                {% if res.mode == 1 %}
                    <script>
                        toastr.error('Password Fields Aren\'t The Same ')
                    </script>
                    {% comment %} <p class="py-2 px-4 text-center rounded-lg bg-red-500 text-white">Password Fields Aren't The Same</p> {% endcomment %}
                {% else %}
                    <script>
                       

                        toastr.warning('Account Already Exists ')
                    </script>
                    {% comment %} <p class="py-2 px-4 text-center rounded-lg bg-yellow-500 text-white">Account Already Exists</p> {% endcomment %}
                {% endif %}
            
            {% endif %}
        {% endif %}
        
         

        <h1 class="py-3 text-3xl text-center">Create Account Now For Free</h1>
        <div class="flex justify-center">
            <form method="POST" action="" class="py-3">
                {% csrf_token %}
                
                <table class="mb-9">
                    <tr class="mb-9">
                        <td><label class="inline-block mb-2">Username :&nbsp;&nbsp;&nbsp; </label></td>
                        <td class="w-[20rem]">
                            <input type="text" name="username" class="w-full py-2 px-6 rounded-md border-2" required>
                        </td>
                    </tr>
                    
                    <tr class="mb-9">
                        <td><label class="inline-block mb-2">Email :&nbsp;&nbsp;&nbsp;</label></td>
                        <td class="w-[20rem]">
                            <input type="text" name="email" class="w-full py-2 px-6 rounded-md border-2"required>
                        </td>
                    </tr> 
                    <tr class="mb-9">
                        <td><label class="inline-block mb-2">Password :&nbsp;&nbsp;&nbsp;</label></td>
                        <td class="w-[20rem]">
                            <input type="password" name="password" class="w-full py-2 px-6 rounded-md border-2" required>
                        </td>
                    </tr>
                    <tr>
                        <td> <label class="inline-block mb-2">Repeat Password :&nbsp;&nbsp;&nbsp;</label></td>
                        <td class="w-[20rem]">
                            <input type="password" name="password1" class="w-full py-2 px-6 rounded-md border-2" required>
                        </td>
                    </tr>
                    
                </table>
                <div class="flex justify-center">
                    <button class="py-2 px-4 text-lg bg-green-500 hover:bg-green-700 rounded-md text-white">Sign Up</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}